// Phase 3 — Model development. The full multi-round loop lives HERE, not in the
// orchestrator: stage pipeline, FIX budget, MCMC throttling, verdict audits,
// the question ledger, plateau guards, and round budgets are all code.
// Judgment happens INSIDE the loop as schema-constrained agent calls:
//
//   critic      — per-experiment statistical + domain assessment
//   strategist  — per-round: close questions, pick explorations, framework
//                 questioning, surface new structural questions, stop
//   refiner     — FIX (repair) and EXPLORE (extend/simplify) variants
//   designer    — experiments for newly surfaced questions
//   selector    — final comparison + coverage audit
//
// The strategist proposes; the script disposes. Every strategist decision is
// filtered through deterministic guards (budgets, plateau rule, caps), and every
// dropped decision is logged — no silent truncation.
//
// Invoked by the orchestrator (see the `orchestration` skill) as:
//
//   Workflow({
//     scriptPath: "${CLAUDE_PLUGIN_ROOT}/workflows/develop.js",
//     args: {
//       projectDir, dataPath,                    // absolute paths
//       questions:   [{id, statement, contrast?}, ...],          // from design.js
//       experiments: [{id, questionId, spec, baseline?, context?}, ...],
//       planPath: "...",       // default: <projectDir>/design/experiment_plan.md
//       edaReportPath: "...",  // default: <projectDir>/eda/eda_report.html
//       metric: { name, definition },  // the plan's ranking metric (design.js
//                              // plan.ranking_metric); default: observation-level
//                              // PSIS-LOO. The script never assumes WHICH metric —
//                              // only its shape (score ± se, higher is better).
//       bounds: "...",         // the plan's outcome plausibility bounds
//                              // (design.js plan.plausibility_bounds) — the prior
//                              // gate's audited number is computed against these
//       limits: { maxRounds: 5, refineBudget: 2, maxMcmcConcurrency: 3,
//                 explorePerQuestion: 2, maxNewQuestions: 2,
//                 maxTotalExperiments: 24, budgetReserve: 60000 },
//     },
//   })
//
// Crash recovery is file-based: stage agents follow the validation-protocol
// status.json contract, so re-running with the same args re-verifies completed
// stages in seconds instead of re-fitting. Same-session, pass resumeFromRunId
// to also replay completed agent calls from the journal. Do NOT edit this file
// while a run that references it is in flight.

export const meta = {
  name: 'develop-models',
  description: 'Phase 3 engine: multi-round validation loop — pipeline, budgets, audits, and question ledger in code; judgment via critic/strategist/refiner/designer/selector agents',
  whenToUse: 'Dispatched by the bayesian-workflow orchestrator during Phase 3. Not intended for direct use.',
  phases: [
    { title: 'Validate', detail: 'per experiment: prior → recovery → fit → ppc → critic, with FIX refinement' },
    { title: 'Judge', detail: 'round strategist: close/explore/new questions/stop' },
    { title: 'Extend', detail: 'refiners and designers produce the next round' },
    { title: 'Select', detail: 'final comparison and coverage audit' },
  ],
}

const A = typeof args === 'string' ? JSON.parse(args) : args
if (!A || !A.projectDir || !A.dataPath || !Array.isArray(A.questions) || !Array.isArray(A.experiments) || A.experiments.length === 0) {
  throw new Error('args must be {projectDir, dataPath, questions:[{id,statement}], experiments:[{id,questionId,spec,baseline?,context?}], planPath?, edaReportPath?, metric?, bounds?, limits?}')
}
const PLAN = A.planPath || `${A.projectDir}/design/experiment_plan.md`
const EDA = A.edaReportPath || `${A.projectDir}/eda/eda_report.html`
// Ranking metric: identity comes from the plan; this script hardcodes only the
// SHAPE a comparison needs (scalar score + se on a shared scale, higher better).
const METRIC = A.metric && A.metric.name
  ? A.metric
  : { name: 'elpd_loo', definition: 'observation-level PSIS-LOO (elpd_loo ± se from loo.json)' }
const L = {
  maxRounds: 5,            // hard cap on strategist-driven rounds
  refineBudget: 2,         // FIX invocations per experiment lifecycle
  maxMcmcConcurrency: 3,   // recovery + fit stages hold a semaphore slot
  explorePerQuestion: 2,   // EXPLORE variants per question across the run
  maxNewQuestions: 2,      // strategist-surfaced questions across the run
  maxTotalExperiments: 24, // lifetime cap incl. variants and gap experiments
  budgetReserve: 60000,    // stop opening new work when tokens run this low
  ...(A.limits || {}),
}
const AGENT = (name) => `bayesian-workflow:${name}`
const M = A.model ? { model: A.model } : {}

// Dispatch seam. Normally resolves the plugin agent by type; A.agentBodies[name]
// (testing outside a plugin-loaded session, or prompt iteration without a
// plugin reload) prepends the role instructions and uses the default subagent.
// agent() THROWS (not null) when a subagent completes without structured
// output — catch it here so every caller sees the same "lost" signal (null)
// and the retry/resubmit machinery engages instead of the lifecycle dying.
const call = async (name, prompt, opts) => {
  try {
    return A.agentBodies && A.agentBodies[name]
      ? await agent(`${A.agentBodies[name]}\n\n=== DISPATCH ===\n\n${prompt}`, { ...opts, ...M })
      : await agent(prompt, { ...opts, agentType: AGENT(name), ...M })
  } catch (e) {
    log(`⚠ ${opts.label || name}: agent failed (${String(e && e.message || e).slice(0, 140)}) — treating as lost`)
    return null
  }
}

// ---------------------------------------------------------------------------
// Structured-output schemas. `rationale` first: models emit properties in
// schema order, so reasoning is committed before the verdict. Stage numeric
// fields are the audit surface (definitions in the validation-protocol skill);
// they are MANDATORY on PASS — enforced by auditGate, not by `required`,
// because a FAIL (e.g. a probe that never sampled) has no LOO to report and
// must never be forced to invent one.
// ---------------------------------------------------------------------------
const gate = (extraProps) => ({
  type: 'object',
  properties: {
    rationale: { type: 'string', description: 'One short paragraph: the evidence behind the verdict' },
    verdict: { enum: ['PASS', 'FAIL'] },
    from_cache: { type: 'boolean', description: 'true iff returned via the validation-protocol completed-work check without redoing work' },
    key_numbers: { type: 'string', description: 'One dense line: the numbers behind the verdict' },
    report_path: { type: 'string' },
    ...extraProps,
  },
  required: ['rationale', 'verdict', 'from_cache', 'key_numbers'],
})

const AUDITED = { description: 'MANDATORY when verdict is PASS (audited); omit only when the stage never computed it (early FAIL)' }
const PROVENANCE = { type: 'string', description: 'Absolute path of the dataset file this stage actually read — audited against the dispatched data_path' }
const PRIOR_RESULT = gate({
  extreme_draw_pct: { type: 'number', description: `% of prior predictive draws outside the ASSIGNED plausibility bounds. ${AUDITED.description}` },
  data_path: PROVENANCE,
  adjustments: { type: 'string', description: 'Prior adjustments made in place (hyperparameters tightened or rescaled in model.stan + prior_model.stan) before the verdict; omit if none' },
})

const RECOVERY_RESULT = gate({
  coverage_90: { type: 'number', description: `Fraction of parameters whose true value lies in the posterior 90% CI. ${AUDITED.description}` },
  max_bias_z: { type: 'number', description: `max over parameters of |posterior mean − true| / posterior sd. ${AUDITED.description}` },
})

const FIT_RESULT = gate({
  rhat_max: { type: 'number', description: AUDITED.description },
  ess_min: { type: 'number', description: AUDITED.description },
  divergences: { type: 'integer', description: AUDITED.description },
  metric_note: { type: 'string', description: 'One line, BEFORE the metric fields: confirm you computed the ASSIGNED metric, or state exactly why you deviated and what you computed instead — a deviated score is excluded from ranking, and an unexplained deviation reads as substitution-for-convenience' },
  metric: { type: 'string', description: `Name of the ranking metric you computed — must be the one assigned in the dispatch. ${AUDITED.description}` },
  score: { type: 'number', description: `Value of the assigned ranking metric (higher is better). ${AUDITED.description}` },
  score_se: { type: 'number', description: `Standard error of the ranking metric. ${AUDITED.description}` },
  pareto_k_bad_pct: { type: 'number', description: `% of observations with Pareto k > 0.7 (observation-level LOO is always computed as a diagnostic, whatever the ranking metric). ${AUDITED.description}` },
  data_path: PROVENANCE,
})

const PPC_RESULT = gate({
  coverage_90: { type: 'number', description: `Fraction of observations inside the 90% posterior predictive interval. ${AUDITED.description}` },
  loo_pit_extreme_pct: { type: 'number', description: '% of LOO-PIT values in the extreme tails (<0.05 or >0.95)' },
})

// Numbers that MUST be present on a PASS verdict, per stage.
const PASS_REQUIRES = {
  prior: ['extreme_draw_pct'],
  recovery: ['coverage_90', 'max_bias_z'],
  fit: ['rhat_max', 'ess_min', 'divergences', 'score', 'score_se', 'pareto_k_bad_pct'],
  ppc: ['coverage_90'],
}

const CRITIC_RESULT = {
  type: 'object',
  properties: {
    rationale: { type: 'string' },
    verdict: { enum: ['VIABLE', 'CONCERNS', 'BROKEN'] },
    top_concern: { type: 'string', description: 'The single highest-priority concern, one line' },
    suggestions: { type: 'array', items: { type: 'string' }, description: 'Concrete improvement suggestions, priority order, empty if none' },
    surprises: { type: 'array', items: { type: 'string' }, description: 'Genuinely unexpected observations (residual structure, collapsing parameters, unused data) — raw material for the strategist, empty if none' },
    from_cache: { type: 'boolean' },
    report_path: { type: 'string' },
  },
  required: ['rationale', 'verdict', 'top_concern', 'suggestions', 'surprises', 'from_cache'],
}

const REFINE_RESULT = {
  type: 'object',
  properties: {
    rationale: { type: 'string' },
    changes_summary: { type: 'string', description: 'What changed in the variant and the expected diagnostic improvement' },
    exhausted: { type: 'boolean', description: 'true if no meaningful change exists (per the exhaustion clause in your instructions)' },
  },
  required: ['rationale', 'changes_summary', 'exhausted'],
}

const STRATEGY_RESULT = {
  type: 'object',
  properties: {
    rationale: { type: 'string', description: 'Round assessment: what was learned about each open question' },
    close: {
      type: 'array',
      items: {
        type: 'object',
        properties: {
          question_id: { type: 'string' },
          resolution: { type: 'string', description: 'The answer and the evidence that settled it (or why it is unresolvable with this data)' },
        },
        required: ['question_id', 'resolution'],
      },
      description: 'Questions now resolved or unresolvable, empty if none',
    },
    explore: {
      type: 'array',
      items: {
        type: 'object',
        properties: {
          parent_id: { type: 'string', description: 'Terminal experiment to derive the variant from' },
          suggestions: { type: 'array', items: { type: 'string' }, minItems: 1 },
        },
        required: ['parent_id', 'suggestions'],
      },
      description: 'EXPLORE variants worth validating next round, empty if none',
    },
    new_questions: {
      type: 'array',
      items: {
        type: 'object',
        properties: {
          statement: { type: 'string', description: 'Contrastive structural question' },
          rationale: { type: 'string', description: 'The surprising evidence that motivates it' },
        },
        required: ['statement', 'rationale'],
      },
      description: 'Genuinely NEW structural questions (not refinements), empty if none',
    },
    framework_concern: { type: 'string', description: 'Population-level framework concern (wrong model class for the DGP, unused data supporting a different framework) — empty string if none' },
    stop: { type: 'boolean', description: 'true when reasonable modifications have stopped helping and remaining questions are closed or unresolvable' },
  },
  required: ['rationale', 'close', 'explore', 'new_questions', 'framework_concern', 'stop'],
}

const DESIGN_RESULT = {
  type: 'object',
  properties: {
    rationale: { type: 'string' },
    experiments: {
      type: 'array', minItems: 1, maxItems: 3,
      items: {
        type: 'object',
        properties: {
          spec: { type: 'string', description: 'Full model spec: likelihood, structure, priors' },
          purpose_in_sequence: { type: 'string' },
        },
        required: ['spec', 'purpose_in_sequence'],
      },
      description: 'Resolution sequence; experiment 1 is the minimal contrast against the supplied baseline',
    },
    proposal_path: { type: 'string' },
  },
  required: ['rationale', 'experiments', 'proposal_path'],
}

const SELECT_RESULT = {
  type: 'object',
  properties: {
    rationale: { type: 'string' },
    best_model_id: { type: 'string' },
    ranking: { type: 'array', items: { type: 'string' }, description: 'Experiment ids, best first' },
    decision: { enum: ['ADEQUATE', 'EXHAUSTED'] },
    coverage: { enum: ['COMPLETE', 'GAPS'] },
    gaps: { type: 'array', items: { type: 'string' }, description: 'Uncovered EDA modeling implications, empty when coverage is COMPLETE' },
    report_path: { type: 'string' },
  },
  required: ['rationale', 'best_model_id', 'ranking', 'decision', 'coverage', 'gaps'],
}

// ---------------------------------------------------------------------------
// Ledger — the machine-readable question/experiment state. Maintained in
// memory here, returned at the end; the orchestrator persists it as
// experiments/ledger.json. Trajectories drive the deterministic plateau rule.
// ---------------------------------------------------------------------------
const ledger = { metric: METRIC.name, data_path: A.dataPath, questions: {}, experiments: {}, newQuestionCount: 0 }
for (const q of A.questions) {
  ledger.questions[q.id] = {
    id: q.id, statement: q.statement, contrast: q.contrast || '',
    status: 'open', resolution: null, plateaued: false, exploreCount: 0, trajectory: [],
  }
}

const expDir = (id) => `${A.projectDir}/experiments/${id}`
const totalExperiments = () => Object.keys(ledger.experiments).length

function registerExperiment(e) {
  ledger.experiments[e.id] = {
    id: e.id, questionId: e.questionId, baseline: !!e.baseline, parentId: e.parentId || null,
    spec: e.spec, status: 'pending', failed_at: null, dir: expDir(e.id), data_path: A.dataPath,
    score: null, score_se: null, critique_verdict: null,
  }
}

function foldResult(res) {
  // res.id is the final variant id (FIX variants replace their parent in place).
  if (!ledger.experiments[res.id]) registerExperiment({ id: res.id, questionId: res.question_id, spec: res.spec || '' })
  const rec = ledger.experiments[res.id]
  rec.status = res.status
  rec.failed_at = res.failed_at || null
  if (res.root_id !== res.id && ledger.experiments[res.root_id]) {
    ledger.experiments[res.root_id].status = 'superseded'
    rec.baseline = ledger.experiments[res.root_id].baseline
  }
  const fit = res.trail.filter((t) => t.stage === 'fit' && t.result && t.result.verdict === 'PASS').pop()
  if (res.status === 'terminal' && fit) {
    rec.critique_verdict = res.critique ? res.critique.verdict : null
    // A score computed under a different metric than the plan's is not on the
    // shared scale — folding it would poison every ranking/plateau decision.
    if (fit.result.metric && fit.result.metric !== METRIC.name) {
      log(`⚠ ${res.id}: fit reported metric '${fit.result.metric}' ≠ plan metric '${METRIC.name}' — score excluded from trajectories and ranking. Fitter's stated reason: ${fit.result.metric_note || 'NONE GIVEN'}`)
    } else {
      rec.score = fit.result.score
      rec.score_se = fit.result.score_se
      const q = ledger.questions[rec.questionId]
      if (q) {
        q.trajectory.push({ id: res.id, score: rec.score, se: rec.score_se, verdict: rec.critique_verdict })
        updatePlateau(q)
      }
    }
  }
}

// Plateau rule (recomputed, not latched): the latest variant must beat the best
// of its predecessors by more than 2·SE(diff). Unpaired SEs are a crude upper
// bound — fine for a guard; the selector does the proper paired comparison.
function updatePlateau(q) {
  const t = q.trajectory.filter((x) => Number.isFinite(x.score) && Number.isFinite(x.se))
  if (t.length < 2) { q.plateaued = false; return }
  const latest = t[t.length - 1]
  const bestPrev = t.slice(0, -1).reduce((a, b) => (b.score > a.score ? b : a))
  q.plateaued = latest.score - bestPrev.score < 2 * Math.sqrt(latest.se ** 2 + bestPrev.se ** 2)
}

function currentBest() {
  return Object.values(ledger.experiments)
    .filter((e) => e.status === 'terminal' && (e.critique_verdict === 'VIABLE' || e.critique_verdict === 'CONCERNS') && Number.isFinite(e.score))
    .reduce((a, b) => (a === null || b.score > a.score ? b : a), null)
}

// ---------------------------------------------------------------------------
// Verdict-vs-numbers audits. Fit thresholds are hard (they define PASS), so an
// inconsistent PASS is DEMOTED to FAIL and enters the FIX loop. The other
// stages' thresholds are heuristics, so inconsistencies are flagged for the
// strategist rather than acted on.
// ---------------------------------------------------------------------------
function auditGate(stageKey, r, expId) {
  if (!r || r.verdict !== 'PASS') return r
  // Provenance: a stage that read a different dataset than dispatched produces
  // results incomparable with every sibling experiment. For fit that poisons
  // the ranking itself — demote; elsewhere flag for the strategist.
  if (r.data_path && r.data_path !== A.dataPath) {
    if (stageKey === 'fit') {
      log(`⚠ ${expId}: fit PASS demoted to FAIL — fit read '${r.data_path}', dispatched '${A.dataPath}'`)
      return { ...r, verdict: 'FAIL', cross_check: 'DEMOTED', rationale: `Audit demotion: wrong dataset (read ${r.data_path}, dispatched ${A.dataPath}). Agent rationale: ${r.rationale}` }
    }
    return flagInconsistent(r, expId, stageKey, `data_path mismatch: read ${r.data_path}`)
  }
  if ((stageKey === 'fit' || stageKey === 'prior') && !r.data_path) {
    r = flagInconsistent(r, expId, stageKey, 'data_path missing — provenance unverifiable')
  }
  if (stageKey === 'fit' && !r.metric) {
    r = flagInconsistent(r, expId, stageKey, `metric name missing — score assumed to be ${METRIC.name}`)
  }
  const missing = (PASS_REQUIRES[stageKey] || []).filter((k) => !Number.isFinite(r[k]))
  if (missing.length) {
    // Fit numbers define PASS and feed the ledger's score trajectories — a fit
    // PASS without them is unverifiable, so it fails into the FIX path. Other
    // stages' missing numbers are flagged for the strategist instead.
    if (stageKey === 'fit') {
      log(`⚠ ${expId}: fit PASS demoted to FAIL — audited numbers missing: ${missing.join(', ')}`)
      return { ...r, verdict: 'FAIL', cross_check: 'DEMOTED', rationale: `Audit demotion: PASS reported without ${missing.join(', ')}. Agent rationale: ${r.rationale}` }
    }
    return flagInconsistent(r, expId, stageKey, `audited numbers missing: ${missing.join(', ')}`)
  }
  if (stageKey === 'fit') {
    const hard = []
    if (r.rhat_max > 1.01) hard.push(`rhat_max=${r.rhat_max}`)
    if (r.divergences > 0) hard.push(`divergences=${r.divergences}`)
    if (r.ess_min < 400) hard.push(`ess_min=${r.ess_min}`)
    if (hard.length) {
      log(`⚠ ${expId}: fit PASS demoted to FAIL — ${hard.join(', ')} violate hard thresholds`)
      return { ...r, verdict: 'FAIL', cross_check: 'DEMOTED', rationale: `Audit demotion (${hard.join(', ')}). Agent rationale: ${r.rationale}` }
    }
    if (r.pareto_k_bad_pct > 10) return flagInconsistent(r, expId, stageKey, `pareto_k_bad_pct=${r.pareto_k_bad_pct}% > 10%`)
    return r
  }
  const soft = {
    prior: () => r.extreme_draw_pct > 10 && `extreme_draw_pct=${r.extreme_draw_pct}% > 10%`,
    recovery: () => (r.coverage_90 < 0.6 && `coverage_90=${r.coverage_90} < 0.6`) || (r.max_bias_z > 3 && `max_bias_z=${r.max_bias_z} > 3`),
    ppc: () => r.coverage_90 < 0.5 && `coverage_90=${r.coverage_90} < 0.5`,
  }[stageKey]
  const reason = soft && soft()
  return reason ? flagInconsistent(r, expId, stageKey, reason) : r
}

function flagInconsistent(r, expId, stageKey, reason) {
  log(`⚠ ${expId}: ${stageKey} PASS inconsistent with reported numbers (${reason})`)
  return { ...r, cross_check: `INCONSISTENT: ${reason}` }
}

// ---------------------------------------------------------------------------
// Stage dispatch. Agents load their own skills and know the methodology; the
// dispatch supplies only args per each agent's SIGNATURE.
// ---------------------------------------------------------------------------
const RETURN_NOTE = `
Return your result via structured output — call it exactly once, as your final action, with your real results (never placeholders; a placeholder return discards your work and the stage is re-run). Set from_cache=true only if you short-circuited on an existing status.json (validation-protocol Step 3). Report the required numeric fields honestly — they are audited against your verdict.`

const STAGES = [
  {
    key: 'prior', agent: 'prior-predictive-checker', mcmc: false, schema: PRIOR_RESULT,
    prompt: (exp, dir) => `experiment_dir: ${dir}
data_path: ${A.dataPath}
output_dir: ${dir}/prior_predictive
${A.bounds ? `plausibility_bounds (from the experiment plan — compute extreme_draw_pct against THESE, not bounds of your own choosing): ${A.bounds}` : ''}
spec (author ${dir}/model.stan from it if absent):
${exp.spec}
${exp.context ? `\ncontext (from the orchestration loop):\n${exp.context}` : ''}${RETURN_NOTE}`,
  },
  {
    key: 'recovery', agent: 'fake-data-checker', mcmc: true, schema: RECOVERY_RESULT,
    prompt: (exp, dir) => `experiment_dir: ${dir}
output_dir: ${dir}/simulation${RETURN_NOTE}`,
  },
  {
    key: 'fit', agent: 'model-fitter', mcmc: true, schema: FIT_RESULT,
    prompt: (exp, dir) => `experiment_dir: ${dir}
data_path: ${A.dataPath}
output_dir: ${dir}/fit
ranking_metric: ${METRIC.name} — ${METRIC.definition}
${exp.context ? `context: ${exp.context}` : ''}${RETURN_NOTE}`,
  },
  {
    key: 'ppc', agent: 'posterior-predictive-checker', mcmc: false, schema: PPC_RESULT,
    prompt: (exp, dir) => `experiment_dir: ${dir}
output_dir: ${dir}/posterior_predictive
experiment_plan_path: ${PLAN}${RETURN_NOTE}`,
  },
]

function semaphore(n) {
  let active = 0
  const waiters = []
  return async (fn) => {
    while (active >= n) await new Promise((res) => waiters.push(res))
    active++
    try { return await fn() } finally {
      active--
      const w = waiters.shift()
      if (w) w()
    }
  }
}
const mcmcSlot = semaphore(L.maxMcmcConcurrency)

function dispatchStage(stage, exp) {
  const run = () => call(stage.agent, stage.prompt(exp, expDir(exp.id)), {
    label: `${exp.id}:${stage.key}`, phase: 'Validate', schema: stage.schema,
  })
  return stage.mcmc ? mcmcSlot(run) : run()
}

// ---------------------------------------------------------------------------
// Per-experiment lifecycle. FAIL with budget left → model-refiner (FIX) writes
// a NEW variant directory; the variant re-enters at the prior stage. Completed
// stage directories are immutable, so status.json records stay trustworthy.
// ---------------------------------------------------------------------------
async function runExperiment(exp0) {
  let exp = { ...exp0 }
  let budget = L.refineBudget
  const trail = []

  lifecycle: while (true) {
    for (const stage of STAGES) {
      let r = await dispatchStage(stage, exp)
      r = auditGate(stage.key, r, exp.id)
      trail.push({ experiment: exp.id, stage: stage.key, result: r })

      if (!r) {
        log(`${exp.id}: ${stage.key} agent lost — will auto-resubmit once next round`)
        return { id: exp.id, root_id: exp0.id, question_id: exp0.questionId, spec: exp.spec, context: exp.context, status: 'agent_lost', failed_at: stage.key, trail }
      }
      if (r.verdict === 'FAIL') {
        if (budget <= 0) {
          log(`${exp.id}: ${stage.key} FAIL, refine budget exhausted — skipping experiment`)
          return { id: exp.id, root_id: exp0.id, question_id: exp0.questionId, spec: exp.spec, context: exp.context, status: 'skipped', failed_at: stage.key, trail }
        }
        budget--
        const variantId = nextId(exp0.id, 'fix')
        log(`${exp.id}: ${stage.key} FAIL — model-refiner (FIX) → ${variantId} (budget left: ${budget})`)
        const ref = await call('model-refiner', `experiment_dir: ${expDir(exp.id)}
mode: FIX
output_dir: ${expDir(variantId)}

suggestions:
Experiment ${exp.id} FAILED the ${stage.key} stage.
Failure rationale: ${r.rationale}
Key numbers: ${r.key_numbers}`, {
          label: `${exp.id}:refine(${stage.key})`, phase: 'Validate', schema: REFINE_RESULT,
        })
        trail.push({ experiment: exp.id, stage: `refine(${stage.key})`, result: ref })
        if (!ref || ref.exhausted) {
          log(`${exp.id}: refiner ${ref ? 'reports options exhausted' : 'lost'} — skipping experiment`)
          return { id: exp.id, root_id: exp0.id, question_id: exp0.questionId, spec: exp.spec, context: exp.context, status: 'skipped', failed_at: stage.key, trail }
        }
        exp = {
          ...exp, id: variantId,
          context: `${exp.context ? exp.context + '\n' : ''}FIX after ${stage.key} failure of ${exp.id}: ${ref.changes_summary}`,
        }
        continue lifecycle // FIX variant re-enters at the prior stage
      }
      log(`${exp.id}: ${stage.key} PASS${r.from_cache ? ' (completed-work check)' : ''}${r.cross_check ? ' ⚠' : ''}`)
      if (stage.key === 'prior' && r.adjustments) {
        // In-place prior tuning changed model.stan; carry it so the ledger,
        // strategist digest, and refiners see the priors that actually ran.
        exp = { ...exp, context: `${exp.context ? exp.context + '\n' : ''}Prior tuning during ${stage.key} of ${exp.id}: ${r.adjustments}` }
      }
    }

    const critique = await call('critic', `experiment_dir: ${expDir(exp.id)}
experiment_plan_path: ${PLAN}
eda_report_path: ${EDA}
data_path: ${A.dataPath}${RETURN_NOTE}`, {
      label: `${exp.id}:critic`, phase: 'Validate', schema: CRITIC_RESULT,
    })
    trail.push({ experiment: exp.id, stage: 'critic', result: critique })
    log(`${exp.id}: critic ${critique ? critique.verdict : 'LOST'}`)
    return {
      id: exp.id, root_id: exp0.id, question_id: exp0.questionId, spec: exp.spec, context: exp.context,
      status: critique ? 'terminal' : 'agent_lost',
      failed_at: critique ? undefined : 'critic',
      trail, critique,
    }
  }
}

// ---------------------------------------------------------------------------
// Strategist digest — a compact, script-composed view of the ledger and the
// round. The strategist reads report files for depth; this is the index.
// ---------------------------------------------------------------------------
function strategistDigest(roundResults, round) {
  const qLines = Object.values(ledger.questions).map((q) => {
    const traj = q.trajectory.map((t) => `${t.id}: ${METRIC.name} ${t.score}±${t.se} [${t.verdict}]`).join('; ') || 'no terminal variants yet'
    const flags = [
      q.plateaued && 'PLATEAUED (no further EXPLORE permitted)',
      q.exploreCount >= L.explorePerQuestion && 'explore budget spent',
    ].filter(Boolean).join(', ')
    return `${q.id} [${q.status}${flags ? '; ' + flags : ''}] ${q.statement}\n  trajectory: ${traj}`
  }).join('\n')

  const rLines = roundResults.map((r) => {
    if (r.status !== 'terminal') return `${r.id}: ${r.status} at ${r.failed_at}`
    const flags = r.trail.filter((t) => t.result && t.result.cross_check).map((t) => `${t.stage}: ${t.result.cross_check}`).join('; ')
    const c = r.critique
    return `${r.id} (${r.question_id}): critique ${c.verdict} — ${c.top_concern}` +
      (c.suggestions.length ? `\n  suggestions: ${c.suggestions.join(' | ')}` : '') +
      (c.surprises.length ? `\n  surprises: ${c.surprises.join(' | ')}` : '') +
      (flags ? `\n  ⚠ audit flags: ${flags}` : '') +
      (c.report_path ? `\n  report: ${c.report_path}` : '')
  }).join('\n')

  return `Round ${round} of ${L.maxRounds}.

QUESTIONS
${qLines}

THIS ROUND
${rLines}

CONSTRAINTS (enforced by the calling script — decisions violating them are dropped)
- EXPLORE variants left per question: ${Object.values(ledger.questions).map((q) => `${q.id}: ${Math.max(0, L.explorePerQuestion - q.exploreCount)}`).join(', ')}
- New-question slots left: ${Math.max(0, L.maxNewQuestions - ledger.newQuestionCount)}
- Experiment slots left: ${Math.max(0, L.maxTotalExperiments - totalExperiments())}
- Plateaued questions accept no EXPLORE; close them or leave them.`
}

// ---------------------------------------------------------------------------
// Guarded application of strategist decisions.
// ---------------------------------------------------------------------------
// Variant/fix ids are globally unique per root: counters skip ids already in
// the ledger, so seeded variants and resubmitted lifecycles never clobber an
// existing experiment directory (whose status.json records must stay valid).
const variantCounter = {}
function nextId(rootId, kind) {
  const base = rootId.replace(/(_(?:v|fix)\d+)+$/, '')
  const key = `${base}:${kind}`
  let n = variantCounter[key] || 0
  let id
  do { id = `${base}_${kind}${++n}` } while (ledger.experiments[id])
  variantCounter[key] = n
  return id
}
const nextVariantId = (rootId) => nextId(rootId, 'v')

async function applyStrategy(strategy) {
  for (const c of strategy.close) {
    const q = ledger.questions[c.question_id]
    if (!q) { log(`✂ close '${c.question_id}' ignored: unknown question`); continue }
    if (q.status !== 'open') { log(`✂ close '${c.question_id}' ignored: already ${q.status}`); continue }
    q.status = 'resolved'
    q.resolution = c.resolution
    log(`${q.id} resolved: ${c.resolution}`)
  }

  // On stop, closes above still apply, but no new work is dispatched — a
  // strategist that says stop AND proposes work is contradictory; stop wins.
  if (strategy.stop) {
    if (strategy.explore.length || strategy.new_questions.length) {
      log(`✂ strategist stop: skipping ${strategy.explore.length} explore(s) and ${strategy.new_questions.length} new question(s) it also proposed`)
    }
    return []
  }

  const work = []

  for (const x of strategy.explore) {
    const parent = ledger.experiments[x.parent_id]
    const q = parent && ledger.questions[parent.questionId]
    const veto =
      !parent ? 'unknown parent' :
      parent.status !== 'terminal' ? `parent is ${parent.status}` :
      !q ? 'parent has no question' :
      q.status !== 'open' ? `question ${q.id} is ${q.status}` :
      q.plateaued ? `question ${q.id} plateaued` :
      q.exploreCount >= L.explorePerQuestion ? `question ${q.id} explore budget spent` :
      totalExperiments() >= L.maxTotalExperiments ? 'experiment cap reached' : null
    if (veto) { log(`✂ explore from ${x.parent_id} dropped: ${veto}`); continue }
    q.exploreCount++
    const vid = nextVariantId(parent.id)
    work.push(() => exploreVariant(parent, x.suggestions, vid))
  }

  for (const nq of strategy.new_questions) {
    if (ledger.newQuestionCount >= L.maxNewQuestions) { log(`✂ new question dropped (slots spent): ${nq.statement}`); continue }
    if (totalExperiments() >= L.maxTotalExperiments) { log(`✂ new question dropped (experiment cap): ${nq.statement}`); continue }
    const best = currentBest()
    if (!best) { log(`✂ new question dropped (no viable best model to baseline from): ${nq.statement}`); continue }
    ledger.newQuestionCount++
    const qid = `q${Object.keys(ledger.questions).length + 1}`
    ledger.questions[qid] = {
      id: qid, statement: nq.statement, contrast: nq.rationale,
      status: 'open', resolution: null, plateaued: false, exploreCount: 0, trajectory: [],
    }
    log(`new question ${qid}: ${nq.statement}`)
    work.push(() => designQuestion(qid, nq, best))
  }

  return (await parallel(work.map((w) => () => w()))).filter(Boolean).flat()
}

async function exploreVariant(parent, suggestions, vid) {
  const ref = await call('model-refiner', `experiment_dir: ${parent.dir}
mode: EXPLORE
output_dir: ${expDir(vid)}

suggestions:
${suggestions.join('\n')}`, {
    label: `explore:${vid}`, phase: 'Extend', schema: REFINE_RESULT,
  })
  if (!ref || ref.exhausted) {
    log(`explore ${vid}: refiner ${ref ? 'reports options exhausted' : 'lost'} — variant not created`)
    return null
  }
  return [{
    id: vid, questionId: parent.questionId, baseline: false, parentId: parent.id,
    spec: `EXPLORE variant of ${parent.id}. Base spec:\n${parent.spec}\n\nChanges: ${ref.changes_summary}`,
    context: `EXPLORE from ${parent.id}: ${ref.changes_summary}`,
  }]
}

async function designQuestion(qid, nq, best) {
  const d = await call('model-designer', `question_id: ${qid}
question: ${nq.statement}
contrast: ${nq.rationale}
baseline_spec (the CURRENT BEST validated model — build on what has been learned, not the original Phase 2 baseline):
${best.spec}
baseline_dir: ${best.dir}

plan_path: ${PLAN}
eda_dir: ${EDA.replace(/\/[^/]*$/, '')}
output_dir: ${A.projectDir}/design/designer_${qid}
max_experiments: 2`, {
    label: `design:${qid}`, phase: 'Extend', schema: DESIGN_RESULT,
  })
  if (!d) { log(`design ${qid}: designer lost — question stays open with no experiments`); return null }
  return d.experiments.slice(0, 2).map((e, j) => ({
    id: `${qid}_e${j + 1}`, questionId: qid, baseline: j === 0,
    spec: e.spec, context: e.purpose_in_sequence,
  }))
}

// ---------------------------------------------------------------------------
// Selection (+ at most one coverage-gap pass).
// ---------------------------------------------------------------------------
async function runSelector(label) {
  const dirs = Object.values(ledger.experiments)
    .filter((e) => e.status === 'terminal' && (e.critique_verdict === 'VIABLE' || e.critique_verdict === 'CONCERNS'))
    .map((e) => e.dir)
  if (!dirs.length) return null
  const qDigest = Object.values(ledger.questions)
    .map((q) => `${q.id} [${q.status}] ${q.statement}${q.resolution ? ` — resolution: ${q.resolution}` : ''}`).join('\n')
  return call('model-selector', `experiment_dirs:
${dirs.join('\n')}
experiment_plan_path: ${PLAN}
eda_report_path: ${EDA}
output_dir: ${A.projectDir}/experiments
ranking_metric: ${METRIC.name} — ${METRIC.definition}
data_path (every listed experiment was validated against this dataset): ${A.dataPath}

Question ledger:
${qDigest}${RETURN_NOTE}`, {
    label, phase: 'Select', schema: SELECT_RESULT,
  })
}

// ---------------------------------------------------------------------------
// The round loop.
// ---------------------------------------------------------------------------
log(`Phase 3: ${A.experiments.length} seed experiment(s), ${A.questions.length} question(s); limits: rounds ${L.maxRounds}, MCMC ${L.maxMcmcConcurrency}, refine ${L.refineBudget}, explore/question ${L.explorePerQuestion}`)

A.experiments.forEach(registerExperiment)
let queue = A.experiments.map((e) => ({ ...e }))
const resubmitted = {}
const allResults = []
let round = 0
let stopReason = null

while (queue.length && round < L.maxRounds) {
  round++
  log(`Round ${round}: ${queue.map((e) => e.id).join(', ')}`)
  const results = (await parallel(queue.map((e) => () => runExperiment(e)))).filter(Boolean)
  allResults.push(...results)
  results.forEach(foldResult)
  queue = []

  // Deterministic post-round rules — before any judgment is consulted.
  for (const r of results) {
    // Baseline failed pre-fit after its FIX attempts → the question is untestable as designed.
    if (r.status === 'skipped' && ['prior', 'recovery'].includes(r.failed_at)) {
      const root = ledger.experiments[r.root_id]
      const q = root && root.baseline && ledger.questions[root.questionId]
      if (q && q.status === 'open') {
        q.status = 'abandoned'
        q.resolution = `baseline ${r.id} failed pre-fit at ${r.failed_at} after refinement — question untestable as designed`
        log(`${q.id} abandoned: ${q.resolution}`)
      }
    }
    // Harness losses get one automatic resubmission of the LAST variant (its
    // completed stages short-circuit on status.json, so it resumes mid-pipeline).
    if (r.status === 'agent_lost' && !resubmitted[r.root_id]) {
      resubmitted[r.root_id] = true
      const orig = ledger.experiments[r.root_id]
      queue.push({
        id: r.id, questionId: orig.questionId, baseline: orig.baseline, spec: r.spec,
        context: `${r.context ? r.context + '\n' : ''}Resubmitted after a harness loss at the ${r.failed_at} stage — completed stages short-circuit on status.json.`,
      })
      log(`${r.id}: auto-resubmitted after harness loss`)
    }
  }
  // Drop queued siblings of abandoned questions.
  queue = queue.filter((e) => {
    const q = ledger.questions[e.questionId]
    if (q && q.status === 'abandoned') { log(`✂ ${e.id} dropped: question ${e.questionId} abandoned`); return false }
    return true
  })

  if (budget.total && budget.remaining() < L.budgetReserve) {
    stopReason = `token budget reserve reached (${Math.round(budget.remaining() / 1000)}k left)`
    log(stopReason + ' — proceeding to selection')
    break
  }

  const strategy = await call('strategist', `${strategistDigest(results, round)}

experiment_plan_path: ${PLAN}
eda_report_path: ${EDA}
experiments_dir: ${A.projectDir}/experiments
output_dir: ${A.projectDir}/experiments/strategy
round: ${round}

Assess the round, then decide: which questions to close, which EXPLORE variants are worth a round, whether any surprise warrants a genuinely NEW structural question, and whether to stop. Read critique reports before trusting one-line summaries. Framework questioning is yours: ask whether the population of models is the right class for this DGP at all.`, {
    label: `strategy:round${round}`, phase: 'Judge', schema: STRATEGY_RESULT,
  })

  if (!strategy) {
    stopReason = 'strategist lost — fail-safe stop'
    log(stopReason + '; proceeding to selection with completed work')
    break
  }
  if (strategy.framework_concern) log(`framework concern: ${strategy.framework_concern}`)

  const newWork = await applyStrategy(strategy)
  newWork.forEach(registerExperiment)
  queue.push(...newWork)

  if (strategy.stop) {
    stopReason = 'strategist: reasonable modifications have stopped helping'
    if (queue.length) log(`strategist stop overrides ${queue.length} queued item(s): ${queue.map((e) => e.id).join(', ')}`)
    queue = []
  } else if (!queue.length) {
    stopReason = 'no new work proposed'
  }
}
if (round >= L.maxRounds && queue.length) {
  stopReason = `round cap ${L.maxRounds} reached with work still queued: ${queue.map((e) => e.id).join(', ')}`
  log(`✂ ${stopReason}`)
}

// --- Selection, with at most one coverage-gap pass ---------------------------
let selection = await runSelector('select')
if (!selection) {
  log('no VIABLE/CONCERNS experiments to select from — returning ledger for orchestrator triage')
} else if (selection.coverage === 'GAPS' && selection.gaps.length && totalExperiments() < L.maxTotalExperiments
  && !(budget.total && budget.remaining() < L.budgetReserve)) {
  const best = currentBest()
  if (!best) {
    log('coverage GAPS but no viable best model to baseline gap experiments from — leaving gaps to the orchestrator')
  } else {
    log(`coverage GAPS: ${selection.gaps.join(' | ')} — one gap pass`)
    if (selection.gaps.length > 2) log(`✂ gap pass capped at 2 of ${selection.gaps.length} gaps`)
    const gapDefs = selection.gaps.slice(0, 2).map((g, i) => ({ qid: `gap${i + 1}`, statement: g }))
    for (const gd of gapDefs) {
      ledger.questions[gd.qid] = { id: gd.qid, statement: gd.statement, contrast: 'selector coverage audit', status: 'open', resolution: null, plateaued: false, exploreCount: 0, trajectory: [] }
    }
    const gapWork = (await parallel(gapDefs.map((gd) => () =>
      designQuestion(gd.qid, { statement: gd.statement, rationale: 'selector coverage audit' }, best),
    ))).filter(Boolean).flat()
    gapWork.forEach(registerExperiment)
    if (gapWork.length) {
      const gapResults = (await parallel(gapWork.map((e) => () => runExperiment(e)))).filter(Boolean)
      allResults.push(...gapResults)
      gapResults.forEach(foldResult)
      selection = (await runSelector('select:post-gap')) || selection
    }
  }
}

// The selector's pick must be a real experiment — an id it misremembered
// would poison the report phase's selectedModelDir.
if (selection && !ledger.experiments[selection.best_model_id]) {
  const fb = currentBest()
  log(`⚠ selector best_model_id '${selection.best_model_id}' not in ledger — falling back to ${fb ? fb.id : 'none'}`)
  if (fb) selection = { ...selection, best_model_id: fb.id }
}

const trailStages = allResults.flatMap((r) => r.trail)
return {
  selection,
  stop_reason: stopReason,
  ledger: {
    metric: ledger.metric,
    data_path: ledger.data_path,
    questions: Object.values(ledger.questions),
    experiments: Object.values(ledger.experiments),
  },
  counts: {
    rounds: round,
    experiments: totalExperiments(),
    terminal: Object.values(ledger.experiments).filter((e) => e.status === 'terminal').length,
    skipped: Object.values(ledger.experiments).filter((e) => e.status === 'skipped' || e.status === 'agent_lost').length,
    cached_stages: trailStages.filter((t) => t.result && t.result.from_cache).length,
  },
}
